// This file was generated by Genii HTML Builder
import {
  Container,
  Typography,
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  Container_850: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '800px',
    height: 'auto',
  },
  Container_9336: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_2432: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '40%',
    height: '100%',
  },
  Typography_1437: {
    fontSize: '23',
    TypographyAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    Typography: 'Craft.js is a React framework for building powerful & feature-rich drag-n-drop page editors.',
  },
  Container_1690: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '60%',
    height: '100%',
  },
  Typography_398: {
    fontSize: '14',
    TypographyAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    Typography: 'Everything you see here, including the editor, itself is made of React components. Craft.js comes only with the building blocks for a page editor; it provides a drag-n-drop system and handles the way user components should be rendered, updated and moved, among other things. <br /> <br /> You control the way your editor looks and behave.',
  },
  Container_7416: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(39, 41, 41, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_4025: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_4466: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '350px',
    height: '250px',
  },
  Container_9129: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '25',
    width: '90%',
    height: '90%',
  },
  Container_7520: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '50',
    width: '80%',
    height: '80%',
  },
  Container_6400: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '50',
    width: '60%',
    height: '60%',
  },
  Container_8775: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'yes',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '55%',
    height: '100%',
  },
  Typography_1335: {
    fontSize: '20',
    TypographyAlign: 'left',
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 1)',
    margin: '0px 0px 18px 0px',
    Typography: 'Design complex components',
  },
  Typography_8029: {
    fontSize: '14',
    TypographyAlign: 'left',
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.8)',
    margin: '0px 0px 0px 0px',
    Typography: 'You can define areas within your React component which users can drop other components into. <br/><br />You can even design how the component should be edited — content editable, drag to resize, have inputs on toolbars — anything really.',
  },
  Container_2577: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(234, 245, 245, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_4584: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0,px 0px 20px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Typography_7023: {
    fontSize: '23',
    TypographyAlign: 'left',
    fontWeight: '500',
    color: 'rgba(46, 47, 47, 1)',
    margin: '0px 0px 0px 0px',
    Typography: 'Programmatic drag & drop',
  },
  Typography_3669: {
    fontSize: '14',
    TypographyAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    Typography: 'Govern what goes in and out of your components',
  },
  Container_8518: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '30px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_347: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '45%',
    height: 'auto',
  },
  Custom1_149: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '20px 20px 20px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(119, 219, 165, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: 'auto',
  },
  Container_8387: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '55%',
    height: 'auto',
  },
  Custom2_2455: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(108, 126, 131, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: '125px',
  },
  Custom3_8482: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '20px 20px 20px 20px',
    margin: '20px 0px 0px 0px',
    background: 'rgba(134, 187, 201, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: 'auto',
  },
});

export default function Home(props) {
  const classes = useStyles(props);

  return (
    <>
      <Container className={classes.Container_850}>
        <Container className={classes.Container_9336}>
          <Container className={classes.Container_2432}>
            <Typography className={classes.Typography_1437}>
              Craft.js is a React framework for building powerful & feature-rich drag-n-drop page editors.
            </Typography>
          </Container>
          <Container className={classes.Container_1690}>
            <Typography className={classes.Typography_398}>
              Everything you see here, including the editor, itself is made of React components. Craft.js comes only with the building blocks for a page editor; it provides a drag-n-drop system and handles the way user components should be rendered, updated and moved, among other things.
              {' '}
              <br />
              {' '}
              <br />
              {' '}
              You control the way your editor looks and behave.
            </Typography>
          </Container>
        </Container>
        <Container className={classes.Container_7416}>
          <Container className={classes.Container_4025}>
            <Container className={classes.Container_4466}>
              <Container className={classes.Container_9129}>
                <Container className={classes.Container_7520}>
                  <Container className={classes.Container_6400} />
                </Container>
              </Container>
            </Container>
            <Container className={classes.Container_8775}>
              <Typography className={classes.Typography_1335}>
                Design complex components
              </Typography>
              <Typography className={classes.Typography_8029}>
                You can define areas within your React component which users can drop other components into.
                {' '}
                <br />
                <br />
                You can even design how the component should be edited — content editable, drag to resize, have inputs on toolbars — anything really.
              </Typography>
            </Container>
          </Container>
        </Container>
        <Container className={classes.Container_2577}>
          <Container className={classes.Container_4584}>
            <Typography className={classes.Typography_7023}>
              Programmatic drag & drop
            </Typography>
            <Typography className={classes.Typography_3669}>
              Govern what goes in and out of your components
            </Typography>
          </Container>
          <Container className={classes.Container_8518}>
            <Container className={classes.Container_347} />
            <Container className={classes.Container_8387} />
          </Container>
        </Container>
      </Container>
    </>
  );
}
