// This file was generated by Genii HTML Builder
import {
  Container,
  Button,
  Typography,
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  Button_1313: {
    color: 'rgba(213, 60, 60, 1)',
    margin: '19px 0px 0px 0px',
  },
  Button_4668: {
  },
});

function Home(props) {
  const classes = useStyles(props);

  return (
    <>
      <Container>
        <Button className={classes.Button_1313} size="small" variant="contained" color="primary">
          Button
        </Button>
        <Container>
          <Typography>
            Hi there
          </Typography>
        </Container>
        <Button className={classes.Button_4668} size="large" variant="outlined" color="secondary">
          Button
        </Button>
      </Container>
    </>
  );
}

export default Home;
